/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import edicion_data_archivos.VolcadoUnidad;
import utils.jTree_ListDevicesVolcado;
import javax.swing.tree.TreePath;
import javax.swing.JTree;

/**
 *
 * @author J
 */
public class VolcadoDeUnidadUI extends javax.swing.JFrame {

    /**
     * Creates new form VolcadoDeUnidadUI
     */
    private jTree_ListDevicesVolcado jTreeFiles = null;
    
    public VolcadoDeUnidadUI() {
        initComponents();
        jTreeFiles = new jTree_ListDevicesVolcado(); 
        jTreeFiles.setJTree(jTree_ListDevicesVolcado);
        jTreeFiles.init(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree_ListDevicesVolcado = new javax.swing.JTree();
        jBtn_Volcado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTree_ListDevicesVolcado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTree_ListDevicesVolcadoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTree_ListDevicesVolcado);

        jBtn_Volcado.setText("Volcar unidad");
        jBtn_Volcado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_VolcadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(235, 235, 235)
                .addComponent(jBtn_Volcado, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 277, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtn_Volcado, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(179, 179, 179))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtn_VolcadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_VolcadoActionPerformed
        // TODO add your handling code here:
        VolcadoUnidad objVolcado = new VolcadoUnidad();
        objVolcado.Volcar("C:\\Users\\J\\Desktop\\fichero1.txt","92AE31A79FEEB2A3");
        
    }//GEN-LAST:event_jBtn_VolcadoActionPerformed

    private void jTree_ListDevicesVolcadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTree_ListDevicesVolcadoMouseClicked
        // TODO add your handling code here:
        String pathSelectedTree = jTreeFiles.GetNodoSelected(evt.getX(), evt.getY());
        System.out.println("pathSelectedTree: " + pathSelectedTree);
    }//GEN-LAST:event_jTree_ListDevicesVolcadoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VolcadoDeUnidadUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VolcadoDeUnidadUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VolcadoDeUnidadUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VolcadoDeUnidadUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VolcadoDeUnidadUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn_Volcado;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree_ListDevicesVolcado;
    // End of variables declaration//GEN-END:variables
}
